FROM node:20-alpine

WORKDIR /app

COPY package.json /app
COPY package-lock.json /app

RUN npm install

COPY . /

CMD ["node", "server.js"]

# commands

# docker build . -t express_server
# docker run express_server
# docker run -p 8080:3000 express_server